name: shopping_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.0+2

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  get: ^4.6.6
  flutter_localizations:
    sdk: flutter
  swipeable_cards_stack: ^1.0.2+1
  hive: ^2.2.3
  carousel_slider: ^4.2.1
  path_provider: ^2.1.1
  modal_progress_hud_nsn: ^0.4.0
  flutter_carousel_slider: ^1.1.0
  firebase_messaging: ^14.6.8
  firebase_core: ^2.16.0
  timeago: ^3.5.0
  intl: ^0.18.1
  lottie: ^2.6.0
  dartz: ^0.10.1
  timelines: ^0.1.0
  persistent_bottom_nav_bar: ^5.0.2
  barcode_widget: ^2.0.3
  # share_plus: ^6.0.0
  flutter_native_splash: ^2.3.3
  change_app_package_name: ^1.1.0
 

dev_dependencies:
  flutter_test:   
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.jpeg"
  min_sdk_android: 21
flutter_native_splash:
  color: "#ffffff"
  image: images/splash.png
  android_gravity: center

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/cairo.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
